name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install libjson-c
      run: sudo apt-get install libjson-c-dev
    - name: Install libc6
      run: sudo apt-get install libc6-dev
    - name: make all
      run: make all
